# Generated by Django 2.2.5 on 2019-12-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=268)),
                ('release_date', models.DateField()),
                ('box_office', models.DecimalField(decimal_places=0, max_digits=11)),
                ('duration', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('genre', models.TextField()),
                ('casts', models.TextField()),
                ('rate', models.FloatField()),
                ('director', models.CharField(max_length=100)),
            ],
        ),
    ]
