# Generated by Django 2.2.5 on 2019-12-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
